package model;

import model.common.AppModule;

import oracle.jbo.ApplicationModule;
import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 05 11:44:28 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for DepartmentView1.
     * @return DepartmentView1
     */
    public ViewObjectImpl getDepartmentView1() {
        return (ViewObjectImpl) findViewObject("DepartmentView1");
    }

    /**
     * Container's getter for EmployeeView1.
     * @return EmployeeView1
     */
    public ViewObjectImpl getEmployeeView1() {
        return (ViewObjectImpl) findViewObject("EmployeeView1");
    }

    /**
     * Container's getter for EmployeeView2.
     * @return EmployeeView2
     */
    public ViewObjectImpl getEmployeeView2() {
        return (ViewObjectImpl) findViewObject("EmployeeView2");
    }

    /**
     * Container's getter for DepartmentView2.
     * @return DepartmentView2
     */
    public ViewObjectImpl getDepartmentView2() {
        return (ViewObjectImpl) findViewObject("DepartmentView2");
    }

    /**
     * Container's getter for DepEmpViewLink1.
     * @return DepEmpViewLink1
     */
    public ViewLinkImpl getDepEmpViewLink1() {
        return (ViewLinkImpl) findViewLink("DepEmpViewLink1");
    }

    /**
     * Container's getter for DepEmpViewLink2.
     * @return DepEmpViewLink2
     */
    public ViewLinkImpl getDepEmpViewLink2() {
        return (ViewLinkImpl) findViewLink("DepEmpViewLink2");
    }
    
    public void iteratingByWhereCondition() {
        ViewObject vo = findViewObject("DepartmentView1");
        
        //vo.defineNamedWhereClauseParam("idDep",null,null);
        //vo.setNamedWhereClauseParam("idDep", new Long(2));        

        vo.defineNamedWhereClauseParam("nmaeDep",null,null);
        vo.setNamedWhereClauseParam("nmaeDep", "% %");
        
        //vo.setWhereClause("ID_DEPARTMENT > :idDep");
        vo.setWhereClause("NAME_DEPARTMENT like :nmaeDep");
        
        vo.executeQuery();
        while (vo.hasNext()) {
            Row row  = vo.next();
            Long id = (Long)row.getAttribute("IdDepartment");
            System.out.println("Department id = "+id.toString());
        }
    }
    
    public void iteratingByViewCriteria() {
        // YOU CAN CREATE VIEW CRITERIA
        ViewObjectImpl voi = (ViewObjectImpl)findViewObject("DepartmentView1");
        ViewCriteria vc = voi.getViewCriteria("Dep_idDepFromDate");
        voi.applyViewCriteria(vc);
        
        
        voi.setNamedWhereClauseParam("idDep", new Long(1));
        voi.setNamedWhereClauseParam("fromdateV", "2022-01-01");
        
        voi.executeQuery();
        while (voi.hasNext()) {
            Row row  = voi.next();
            String name = (String)row.getAttribute("NameDepartment");
            System.out.println("Department name = "+name);
        }
    }

    /**
     * Container's getter for UserTableView1.
     * @return UserTableView1
     */
    public ViewObjectImpl getUserTableView1() {
        return (ViewObjectImpl) findViewObject("UserTableView1");
    }
}

