package model;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 06 15:08:44 CEST 2023
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeeImpl extends EntityImpl {
    /**
     * Validation method for NameBadge.
     */
    public boolean validateNameBadge(String namebadge) {
        String firstLetter = "";
        firstLetter = namebadge.trim().substring(0, 1);
        if (firstLetter.equals("J") || firstLetter.equals("j")) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        IdEmployee,
        NameEmployee,
        MailDepartment,
        NumberCell,
        NameBadge,
        IdDepartment,
        Department,
        DepartmentView1;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int IDEMPLOYEE = AttributesEnum.IdEmployee.index();
    public static final int NAMEEMPLOYEE = AttributesEnum.NameEmployee.index();
    public static final int MAILDEPARTMENT = AttributesEnum.MailDepartment.index();
    public static final int NUMBERCELL = AttributesEnum.NumberCell.index();
    public static final int NAMEBADGE = AttributesEnum.NameBadge.index();
    public static final int IDDEPARTMENT = AttributesEnum.IdDepartment.index();
    public static final int DEPARTMENT = AttributesEnum.Department.index();
    public static final int DEPARTMENTVIEW1 = AttributesEnum.DepartmentView1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public EmployeeImpl() {
    }

    /**
     * @param idEmployee key constituent
     * @param nameEmployee key constituent
     * @param mailDepartment key constituent
     * @param numberCell key constituent
     * @param nameBadge key constituent
     * @param idDepartment key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Long idEmployee, String nameEmployee, String mailDepartment, String numberCell,
                                       String nameBadge, Long idDepartment) {
        return new Key(new Object[] { idEmployee, nameEmployee, mailDepartment, numberCell, nameBadge, idDepartment });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("model.Employee");
    }


}

