package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Apr 05 11:48:21 CEST 2023
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void iteratingByWhereCondition();

    void iteratingByViewCriteria();
}

